### ISSUE TITLE
Better handeling of image for the interests.

### ISSUE THREAD

**Issue by P6g9YHK6** [lehaSVV2009/resume#15]
In place of having to tweak the Interests.js file why no having it checking for a name match in the images folder ?
for exemple if my interest is "football" it would check for football.png/jpg/gif then only show the wildcard.
this would allow for more hands-off approach when it comes to a non forked container.

**Comment by lehaSVV2009** [comment]
There is an undocumented property with name "image" in interests json. E.g. 
```
interests: [{
  name: "football",
  image: "https://cdn.dribbble.com/users/923520/screenshots/4436772/salah-animation-gif.gif"
}, {
  name: "skiing",
  image: "https://lehasvv2009.github.io/resume/static/media/snowboarding.30404734.gif"
}]
```
